---

- name: install packages
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - corosync
    - pacemaker

- name: systemd
  systemd:
    name   : corosync
    enabled: yes
    state  : started
    
