---
# haclusterにパスワードを設定

- name: Create salt
  shell: "mktemp -u | awk '{print substr($0, length($0)-8+1)}'"
  register: salt

- name: Create hash for password
  shell: python -c 'import crypt; print crypt.crypt("{{ password }}", "$6${{ salt.stdout }}")'
  register: hash_password

- name: Modify User
  user:
    name    : hacluster
    password: "{{ hash_password.stdout }}"
    
